### ISSUE TITLE
Лучше считать сумму на стороне БД.

### ISSUE THREAD

**Issue by homich77** [SlavaKyrai/PetShopHomework#1]
https://github.com/SlavaKyrai/PetShopHomework/blob/84c48bfbfd285409cf28a89dfd1a4fb2a33d133b/shop_app/views.py#L136

https://github.com/SlavaKyrai/PetShopHomework/blob/84c48bfbfd285409cf28a89dfd1a4fb2a33d133b/shop_app/views.py#L139

**Пример**:
Cart.objects.annotate(total_sum=Sum('product_price'))

**Comment by SlavaKyrai** [comment]
Поправил модель для подсчёта суммы
https://github.com/SlavaKyrai/PetShopHomework/blob/080d8f0b8ad81783d01924792915d73704a203af/shop_app/models.py#L88-L96
И теперь подсчитываю через аггрегацию
https://github.com/SlavaKyrai/PetShopHomework/blob/080d8f0b8ad81783d01924792915d73704a203af/shop_app/views.py#L131-L132
