### ISSUE TITLE
Если в корзину добавить один и тот же продукт - это будут разные записи. Не совсем корректное поведение.

### ISSUE THREAD

**Issue by homich77** [SlavaKyrai/PetShopHomework#4]
https://github.com/SlavaKyrai/PetShopHomework/blob/84c48bfbfd285409cf28a89dfd1a4fb2a33d133b/shop_app/views.py#L160

**Comment by SlavaKyrai** [comment]
Пофиксил.  Сначала проверяю, есть ли уже заказ с заданным товаром, если есть обновляю количество, иначе создаю новый

https://github.com/SlavaKyrai/PetShopHomework/blob/9644c324a8044854bda03b056ea25ef94166f5b3/shop_app/views.py#L151-L158

**Comment by homich77** [comment]
Отлично. Спасибо
