### ISSUE TITLE
Даже ошибки должны выводится на шаблоне, чтобы было стилистическое соответствие в решении проекта

### ISSUE THREAD

**Issue by homich77** [SlavaKyrai/PetShopHomework#5]
https://github.com/SlavaKyrai/PetShopHomework/blob/84c48bfbfd285409cf28a89dfd1a4fb2a33d133b/shop_app/views.py#L174

**Comment by SlavaKyrai** [comment]
Переделал поиск, добавил во вью с выводом списка
https://github.com/SlavaKyrai/PetShopHomework/blob/09262d6c1796479f316ba761ecc9726b929705db/shop_app/views.py#L12-L22

Может здесь можно было б добавить на проверку пустая ли форма с помощью js в шаблоне.
Оставил возможность отправки пустой формы, которая вернёт список всех товаров. Про вывод ошибок учту
